# ETH3D Low-Resolution, Multi-View Delivery Area Dataset

# Dataset Details
dataset_dir: "/oscar/data/bkimia/jhan192/dataset"
output_dir: "/oscar/data/bkimia/jhan192/jue_dev_ebvo/Edge_Based_Visual_Odometry/outputs"
sequence_name: "training/cables_2"
dataset_type: "ETH3D"

# Stereo Intrinsic Parameters
left_camera:
  resolution: [942, 489]
  intrinsics: [726.28741455078, 726.28741455078, 354.6496887207, 186.46566772461]
  distortion_coefficients: [0, 0, 0, 0]

right_camera:
  resolution: [942, 489]
  intrinsics: [726.04388427734, 726.04388427734, 385.73248291016, 262.19641113281]
  distortion_coefficients: [0, 0, 0, 0]

# Stereo Extrinsic Parameters
stereo:
  #Left Image to Right Image
  R21:
  - [1.000000000000000, 0.000000000000000, 0.000000000000000]
  - [0.000000000000000, 1.000000000000000, 0.000000000000000]
  - [0.000000000000000, 0.000000000000000, 1.000000000000000]

  T21: [-0.059891300000001, 0.000000000000001, 0.000000000000001]
  
  F21: 
  - [0.000000000000000,   0.000000000000000,  0.000000000000000]
  - [0.000000000000000,  0.000000000000000,   0.000110548689097]
  - [0.000000000000000,  -0.000110548689097,  0.000000000000000]

  #Right Image to Left Image
  R12:
  - [1.000000000000000,  0.000000000000000,  0.000000000000000]
  - [0.000000000000000,   1.000000000000000,  0.000000000000000]
  - [0.000000000000000,   0.000000000000000,   1.000000000000000]

  T12: [0.059891300000001, -0.000000000000001, -0.000000000000001]
  
  F12: 
  - [0.000000000000000,  0.000000000000000,   0.000000000000000]
  - [0.000000000000000,  0.000000000000000,  -0.000110548689097]
  - [0.000000000000000,   0.000110548689097,  0.000000000000000]

  focal_length: 541.764